mqtt:
    image: eclipse-mosquitto:latest
    container_name: my-mqtt-container
    ports:
        - 1883:1883
        - 9001:9001
    volumes:
    - ./config/mqtt:/mqtt/config
    - ./log/mqtt:/mqtt/log
    - ./data/mqtt:/mqtt/data/
