# Docker Compose Yaml 
version: "3.5"
services:
    mqtt:
        image: eclipse-mosquitto:1.5.5
        hostname: mosquitto
        container_name: my-mqtt-container
        restart: unless-stopped
        ports:
            - 1883:1883
            - 9001:9001
        networks: 
            - webnet
        volumes:
        - ./config/mqtt:/mqtt/config
        - /Volumes/docker/docker/mqtt/log:/mosquitto/log
        - /Volumes/docker/docker/mqtt/data:/mosquitto/data/

    web:
        image: nginx:1.15
        container_name: my-nginx-container
        restart: always
        volumes:
            - /Volumes/docker/docker/nginx/www:/usr/share/nginx/html
            - /Volumes/docker/docker/nginx/log:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - webnet

    node-red:
        build: ./images/node-red
        image: node-red
        container_name: my-node-red
        restart: always
        ports:
            - 1880:1880
        volumes:
            - /Volumes/docker/docker/node-red-data:/data

    influxdb:
        build: ./images/influxdb
        image: influxdb
        container_name: influxdb
        env_file: configuration.env
        restart: always
        ports:
            - 8086:8086
            - 8082:8082
        networks:
            - influxdb
        volumes:
            - /Volumes/docker/docker/influxdb/data:/var/lib/influxdb

    chronograf:
        image: chronograf
        container_name: chronograf
        restart: always
        entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
        ports:
            - 8888:8888
        networks:
            - influxdb
        depends_on:
            - influxdb
        volumes:
            - /Volumes/docker/docker/chronograf/data:/var/lib/chronograf/
    
    grafana:
        build: ./images/grafana
        image: grafana
        container_name: grafana
        env_file: configuration.env
        restart: always
        depends_on:
            - influxdb
        networks:
            - influxdb
        ports:
            - 3000:3000
        volumes:
            - /Volumes/docker/docker/grafana/data:/var/lib/grafana


networks:
    webnet: {}
    influxdb: {}

