# Docker Compose Yaml 
version: "3.5"
services:
    mqtt:
        image: eclipse-mosquitto:1.5.5
        hostname: mosquitto
        container_name: my-mqtt-container
        restart: unless-stopped
        ports:
            - 1883:1883
            - 9001:9001
        networks: 
            - webnet
        volumes:
        - ./config/mqtt:/mqtt/config
        - ./log/mqtt:/mqtt/log
        - ./data/mqtt:/mqtt/data/

    web:
        image: nginx:1.15
        container_name: my-nginx-container
        restart: always
        volumes:
            - /Volumes/docker/docker/nginx/www:/usr/share/nginx/html
            - /Volumes/docker/docker/nginx/log:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - webnet

    homeassistant:
        container_name: home-assistant
        image: homeassistant/home-assistant
        volumes:
            - ./config/home-assistant:/config
#           - /etc/localtime:/etc/localtime:ro
        restart: always
        ports:
            - 8123:8123

    node-red:
        build: node-red
        container_name: my-node-red
        restart: always
        ports:
            - 1880:1880
        volumes:
            - /Volumes/docker/docker/node-red-data:/data

    influxdb:
        build: influxdb
        container_name: influxdb
        env_file: configuration.env
        restart: always
        ports:
            - 8086:8086
        networks:
            - influxdb
        volumes:
            - /Volumes/docker/docker/influxdb-data:/var/lib/influxdb

    chronograf:
        image: chronograf
        container_name: chronograf
        restart: always
        entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
        ports:
            - 8888:8888
        networks:
            - influxdb
        depends_on:
            - influxdb
    
    grafana:
        build: grafana
        container_name: grafana
        env_file: configuration.env
        restart: always
        depends_on:
            - influxdb
        networks:
            - influxdb
        ports:
            - 3000:3000
        volumes:
            - /Volumes/docker/docker/grafana-data:/var/lib/grafana

    # openhab:
    #     image: "openhab/openhab:2.4.0"
    #     env_file: configuration.env
    #     restart: always
    # #    network_mode: host
    #     ports:
    #         - 8080:8080
    #         - 8443:8443
    #     volumes:
    #     # - "/etc/localtime:/etc/localtime:ro"
    #     # - "/etc/timezone:/etc/timezone:ro"
    #     - "./openhab_addons:/openhab/addons"
    #     - "./openhab_conf:/openhab/conf"
    #     - "./openhab_userdata:/openhab/userdata"


# volumes:
#     openhab_addons:
#         driver: local
#     openhab_conf:
#         driver: local
#     openhab_userdata:
#         driver: local

networks:
    webnet: {}
    influxdb: {}

#volumes:
#    grafana_data: {}
#    influxdb_data: {}