version: "3"
services:
  web:
    image: nginx
    volumes:
      - /mnt/nassau/docker/nginx/www:/usr/share/nginx/html
      - /mnt/nassau/docker/nginx/log:/var/log/nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
networks:
   webnet:
