{
 "title": "DPI",
 "tags": [
  "pfSense",
  "NTOP"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ndpicat",
    "query": "SHOW TAG VALUES FROM \"iface:ndpi\" WITH KEY=protocol"
   }
  ]
 },
 "panels": [
  {
   "title": "IPv4 Traffic by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "IPV4 $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:traffic",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Interface igb1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffix Distribution V4/V6",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "IPv4",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "host:traffic",
     "query": "select sum(sumtx_sumrx) from (select sumtx+sumrx from (select sum(tx) as sumtx, sum(rx) as sumrx from (SELECT non_negative_difference(\"bytes_rcvd\") as rx,non_negative_difference(\"bytes_sent\") as tx FROM \"host:traffic\" WHERE (\"host\" =~ /^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$/) AND $timeFilter GROUP BY \"host\") group by *))",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=~",
       "value": "/^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$/"
      }
     ]
    },
    {
     "alias": "IPv6",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "host:traffic",
     "query": "select sum(sumtx_sumrx) from (select sumtx+sumrx from (select sum(tx) as sumtx, sum(rx) as sumrx from (SELECT non_negative_difference(\"bytes_rcvd\") as rx,non_negative_difference(\"bytes_sent\") as tx FROM \"host:traffic\" WHERE (\"host\" !~ /^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}/) AND $timeFilter GROUP BY \"host\") group by *))",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=~",
       "value": "/^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$/"
      }
     ]
    }
   ]
  },
  {
   "title": "NDPI Interface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 8 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "protocol" ], "type": "tag" }
     ],
     "measurement": "iface:ndpi",
     "query": "SELECT \"bytes\" as bytes FROM \"iface:ndpi\" WHERE $timeFilter GROUP BY \"protocol\"",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "protocol", "operator": "=~", "value": "/^$ndpicat$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic egress+ingress per Country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "country:traffic",
     "query": "select sum(inout)/1024/1024/1024 from (SELECT \"bytes_ingress\"+\"bytes_egress\" as inout FROM \"country:traffic\" WHERE time >= now() - 3h GROUP BY \"country\") group by *",
     "select": [
      [
       { "params": [ "bytes_egress" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flowthroughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "local2remote",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "iface:local2remote",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "remote2local",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "iface:remote2local",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "protocol" ], "type": "tag" }
     ],
     "measurement": "iface:ndpi",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "protocol", "operator": "=~", "value": "/^$ndpicat$/" }
     ]
    }
   ]
  }
 ]
}